# Copyright © 2019-present gsfernandes81

# This file is part of "dd" henceforth referred to as "destiny-director".

# destiny-director is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.

# "destiny-director" is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License along with
# destiny-director. If not, see <https://www.gnu.org/licenses/>.

"""The Alembic migrations must build exactly the schema the models describe.

Two independent checks, each against a *fresh* database:

* ``alembic upgrade head`` then ``alembic check`` — alembic's own autogenerate
  comparison, run through ``migrations/env.py`` (so the env's compare options are
  exercised too), must find nothing left to do.
* ``alembic upgrade head`` on one database vs ``Base.metadata.create_all`` on
  another — the reflected tables, columns, primary keys, indexes and unique
  constraints must match.

SQLite always; Postgres as well when ``TEST_USE_POSTGRES`` is set (each check gets
its own scratch database, created and dropped here)."""

import os
import typing as t
from collections.abc import Callable, Iterator
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import create_engine, inspect, make_url, text

from dd.common import cfg, schemas

pytestmark = pytest.mark.integration

REPO_ROOT = Path(__file__).resolve().parents[3]

# (async URL for alembic, sync URL for reflection) of a database that starts empty.
DbFactory = Callable[[str], tuple[str, str]]


def _alembic_config(url: str) -> Config:
    """An alembic Config pointed at this repo's environment and at ``url``.

    ``env.py`` prefers an explicitly-set ``sqlalchemy.url`` over ``cfg``, which is how
    these tests aim it at a throwaway database; ``configure_logging`` off keeps it from
    reconfiguring the root logger mid-test-run."""
    config = Config(str(REPO_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(REPO_ROOT / "migrations"))
    config.set_main_option("sqlalchemy.url", url)
    config.attributes["configure_logging"] = False
    return config


@pytest.fixture(params=["sqlite", "postgres"])
def fresh_db(request: pytest.FixtureRequest, tmp_path: Path) -> Iterator[DbFactory]:
    """Hand out empty databases by name, cleaning them up afterwards."""
    if request.param == "sqlite":

        def sqlite_db(name: str) -> tuple[str, str]:
            path = tmp_path / f"{name}.db"
            return f"sqlite+aiosqlite:///{path}", f"sqlite:///{path}"

        yield sqlite_db
        return

    if not os.getenv("TEST_USE_POSTGRES"):
        pytest.skip("TEST_USE_POSTGRES not set")
    if not schemas._db_is_local():
        pytest.skip("configured Postgres is not local — refusing to create scratch DBs")

    created: list[str] = []
    admin = create_engine(cfg.db_url, isolation_level="AUTOCOMMIT")

    def postgres_db(name: str) -> tuple[str, str]:
        db_name = f"dd_migration_test_{os.getpid()}_{name}"
        with admin.connect() as conn:
            conn.execute(text(f'DROP DATABASE IF EXISTS "{db_name}"'))
            conn.execute(text(f'CREATE DATABASE "{db_name}"'))
        created.append(db_name)
        # render_as_string, not str(): the latter masks the password with "***".
        return (
            make_url(cfg.db_url_async)
            .set(database=db_name)
            .render_as_string(hide_password=False),
            make_url(cfg.db_url)
            .set(database=db_name)
            .render_as_string(hide_password=False),
        )

    try:
        yield postgres_db
    finally:
        with admin.connect() as conn:
            for db_name in created:
                conn.execute(text(f'DROP DATABASE IF EXISTS "{db_name}" WITH (FORCE)'))
        admin.dispose()


def _snapshot(sync_url: str) -> dict[str, dict[str, t.Any]]:
    """The structure of every table in ``sync_url``, as plain comparable data.

    CHECK constraints are left out: the models declare them unnamed, so the backends
    invent their own names and reflection cannot line them up (the same reason
    ``env.py`` excludes them from autogenerate)."""
    engine = create_engine(sync_url)
    try:
        inspector = inspect(engine)
        return {
            table: {
                "columns": {
                    col["name"]: (str(col["type"]), bool(col["nullable"]))
                    for col in inspector.get_columns(table)
                },
                "primary_key": tuple(
                    inspector.get_pk_constraint(table)["constrained_columns"]
                ),
                "indexes": sorted(
                    (str(ix["name"]), tuple(ix["column_names"]), bool(ix["unique"]))
                    for ix in inspector.get_indexes(table)
                ),
                "unique_constraints": sorted(
                    (str(uq["name"]), tuple(uq["column_names"]))
                    for uq in inspector.get_unique_constraints(table)
                ),
            }
            for table in sorted(inspector.get_table_names())
            if table != "alembic_version"
        }
    finally:
        engine.dispose()


def test_upgrade_head_matches_metadata(fresh_db: DbFactory) -> None:
    """After ``upgrade head`` an autogenerate run must come out empty."""
    async_url, _ = fresh_db("migrated")
    config = _alembic_config(async_url)

    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"migrations have drifted from schemas.Base.metadata: {exc}")


def test_upgrade_head_matches_create_all(fresh_db: DbFactory) -> None:
    """``upgrade head`` and ``create_all`` must build the same schema."""
    migrated_async, migrated_sync = fresh_db("migrated")
    created_async, created_sync = fresh_db("created")

    command.upgrade(_alembic_config(migrated_async), "head")

    engine = create_engine(created_sync)
    try:
        schemas.Base.metadata.create_all(engine)
    finally:
        engine.dispose()

    assert _snapshot(migrated_sync) == _snapshot(created_sync)
