# Copyright © 2019-present gsfernandes81

# This file is part of "dd" henceforth referred to as "destiny-director".

# destiny-director is free software: you can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.

# "destiny-director" is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License along with
# destiny-director. If not, see <https://www.gnu.org/licenses/>.

"""Snapshot a Railway environment's service variables, put them back, and compare them.

The cutover ends by deleting a dozen legacy variables, and Railway keeps no history —
``SHEETS_PRIVATE_KEY`` is a Google service-account key you would not get back, and the
Discord and Bungie secrets are no better. This takes the snapshot first
(``make dump-vars``) and can restore from it (``make restore-vars``).

**The file holds live secrets in plaintext.** It is written to the repo root, where
``kyber-*-vars-*.json`` is gitignored alongside the ``.sql`` dumps. Treat it exactly
like the database dumps: keep it, do not commit it, do not paste it.

**Two input formats, and they are not equally good.**

``dump`` reads the CLI, which *renders* references: ``railway variables`` returns the
resolved value of ``${{Postgres.DATABASE_URL}}`` under both ``--json`` and ``--kv``,
with no way to read the reference itself. A dump is therefore a faithful record of the
**values** and a lossy record of the **definitions**.

``restore-raw`` reads a paste of Railway's web **Raw Editor**, which is the authoring
surface and so shows references unresolved. That is the only way to get
``${{shared.SHEETS_PRIVATE_KEY}}`` back as a reference rather than as a flattened copy,
and it matters more than it sounds: a large share of this project's variables are
``${{shared.*}}``, defined once at the environment level and referenced by both bots.
The CLI cannot see that scope at all — ``railway variables`` is per-service.

**What is never written back**, in either format:

- ``RAILWAY_*`` — injected by the platform per deploy, not settable.
- a **literal** ``DATABASE_*`` / ``MYSQL_*`` — Railway reassigns the public TCP proxy's
  port when a database service is recreated, so a flattened literal pins a stale
  host:port. Absent fails at boot; stale fails at connect, later, looking like a network
  problem. A ``${{...}}`` reference under those names is fine and *is* restored — it
  re-links rather than freezing.
- anything whose live value already matches — writing it would only churn the service.

So the rule is about the value's shape, not its name.

**And a third thing it does**: ``compare`` (``make vars-check``) lists the variables
beacon has and anchor does not — the one asymmetry that costs something, since every
cutover step runs under anchor. See the parity section below.
"""

import argparse
import datetime as dt
import json
import pathlib
import re
import subprocess
import sys
import typing as t

#: The services whose variables are worth capturing: the two bots. The database
#: services' variables are generated by Railway from the volume, so a snapshot of them
#: would be a snapshot of something that regenerates itself.
DEFAULT_SERVICES: tuple[str, ...] = ("anchor", "beacon")

#: Injected by Railway per deploy; setting them is meaningless.
_PLATFORM_PREFIX = "RAILWAY_"

#: Safe as a reference, dangerous as a flattened literal — see the module docstring.
#: Matched on prefix AND the ``_URL`` suffix, not the prefix alone: the hazard is a
#: pinned host:port, so it is the URLs that must not be copied. ``MYSQL_SSL=false``
#: shares the prefix and is perfectly restorable — a prefix-only rule dropped it.
_ROTATING_PREFIXES: tuple[str, ...] = ("DATABASE_", "MYSQL_")
_ROTATING_SUFFIX = "_URL"

#: Names that belong to one bot and not the other, so their absence from the other is
#: correct rather than drift. Only ``DISCORD_TOKEN_BEACON`` can ever be reported by
#: :func:`beacon_only` — the anchor entries are here to say what the map means, since a
#: beacon-only view can never reach them.
_SERVICE_SCOPED: dict[str, str] = {
    "DISCORD_TOKEN_ANCHOR": "anchor",
    "DISCORD_TOKEN_BEACON": "beacon",
    "DISCORD_OAUTH_CLIENT_ID": "anchor",
    "DISCORD_OAUTH_CLIENT_SECRET": "anchor",
    "DEV_AUTH_USER_ID": "anchor",
    "PORT": "anchor",
    "PUBLIC_BASE_URL": "anchor",
}

#: Railway's reference syntax — ``${{shared.FOO}}``, ``${{Postgres.DATABASE_URL}}``.
_REFERENCE = re.compile(r"^\$\{\{[^}]+\}\}$")

#: A POSIX environment-variable name. Anything else in a pasted name is a copy artefact
#: — a non-breaking space picked up from a web page renders identically to a space and
#: would otherwise create a second, wrong variable that looks right in every listing.
_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

#: Wrappers a terminal adds around a paste when bracketed-paste mode is on. An artefact
#: of the transport, not of the data, so they are removed rather than complained about.
_BRACKETED_PASTE = re.compile(r"\x1b\[20[01]~")

#: Control characters that have no business in an environment value. Tab, newline and
#: carriage return are spared — a genuinely multi-line value is legal, if unusual. The
#: rest are rejected because they reach a terminal eventually: a value carrying an ANSI
#: escape can rewrite whatever prints it, and no real setting needs one.
_CONTROL = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f]")


class RailwayVarsError(Exception):
    """A problem that should stop the dump or restore rather than half-finish it."""


def _railway(args: list[str]) -> str:
    """Run the Railway CLI, or raise with whatever it said about why it could not."""
    try:
        done = subprocess.run(
            ["railway", *args], capture_output=True, text=True, check=False
        )
    except FileNotFoundError as e:  # pragma: no cover - environment-dependent
        raise RailwayVarsError(
            "the `railway` CLI is not on PATH — the dev container ships it, or "
            "install it locally"
        ) from e
    if done.returncode != 0:
        why = done.stderr.strip() or done.stdout.strip()
        raise RailwayVarsError(f"`railway {' '.join(args)}` failed: {why}")
    return done.stdout


def fetch(service: str, environment: str) -> dict[str, str]:
    """Every variable Railway reports for one service, references already rendered."""
    raw = _railway(["variables", "-s", service, "-e", environment, "--json"])
    try:
        loaded = json.loads(raw)
    except json.JSONDecodeError as e:
        raise RailwayVarsError(f"{service}: railway returned non-JSON output") from e
    if not isinstance(loaded, dict):
        raise RailwayVarsError(f"{service}: expected an object of variables")
    return {str(k): "" if v is None else str(v) for k, v in loaded.items()}


def is_reference(value: str) -> bool:
    """Whether ``value`` is a Railway reference rather than a literal."""
    return bool(_REFERENCE.match(value.strip()))


def restorable(name: str, value: str = "") -> tuple[bool, str]:
    """Whether to write ``name`` back, and if not, why not."""
    if name.startswith(_PLATFORM_PREFIX):
        return False, "platform-injected"
    if is_reference(value):
        # A reference re-links on write, so it cannot go stale the way a copy can.
        return True, ""
    if name.startswith(_ROTATING_PREFIXES) and name.endswith(_ROTATING_SUFFIX):
        return False, "literal database URL — would pin a host:port that rotates"
    return True, ""


# --- parity ---------------------------------------------------------------------------
#
# One question, deliberately: **which variables does beacon have that anchor does not?**
#
# That is the asymmetry that costs something. `cutover-settings` and every other cutover
# step run under anchor (RAILWAY_SERVICE), so a variable set only on beacon is read by
# nothing during the migration and its value is quietly replaced by a default. It is not
# hypothetical — DEFAULT_URL and DISABLE_BAD_CHANNELS were in exactly that state, found
# by hand, which is what this exists to do instead.
#
# The reverse direction is not reported. Anchor legitimately holds more than beacon (it
# serves the web UI), so anchor-only names are ordinary rather than interesting, and a
# check that lists them is one people stop reading.


def _platform(name: str) -> bool:
    """Injected by Railway per deploy — present or absent by its choice, not ours."""
    return name.startswith(_PLATFORM_PREFIX)


def beacon_only(anchor: dict[str, str], beacon: dict[str, str]) -> list[str]:
    """Names beacon holds and anchor does not, minus the ones that mean nothing."""
    return sorted(
        name
        for name in beacon
        if name not in anchor
        and not _platform(name)
        and _SERVICE_SCOPED.get(name) != "beacon"
    )


def _do_compare(args: argparse.Namespace) -> int:
    anchor = fetch("anchor", args.environment)
    beacon = fetch("beacon", args.environment)
    names = beacon_only(anchor, beacon)

    print(f"On beacon and not on anchor, in {args.environment}:")
    if not names:
        print("  none")
        return 0
    for name in names:
        print(f"  {name}")
    print(
        f"\n{len(names)} variable(s). Every cutover step runs under anchor, so nothing "
        "reads these\nduring the migration. Names only — the values are secrets."
    )
    return 1


def parse_raw(text: str) -> dict[str, str]:
    """Variables from a paste of Railway's web Raw Editor.

    The format is ``KEY="value"`` with the value **JSON-encoded** — inner quotes arrive
    as ``\\"``, which is exactly what ``json.loads`` undoes. Decoding it as JSON rather
    than stripping quotes by hand is what keeps ``SHEETS_PRIVATE_KEY`` intact: its value
    contains literal backslash-n sequences, and hand-rolled unquoting either mangles
    them into real newlines or leaves a doubled backslash. Both look plausible and both
    are wrong.

    Unquoted values are accepted verbatim, so a hand-edited file still works.
    """
    # Strip what the *transport* added before parsing what the user meant: a leading
    # BOM (a browser copy can carry one) and bracketed-paste wrappers. Left in place,
    # both attach themselves to the first variable's name and produce a plausible-
    # looking variable nobody asked for.
    text = _BRACKETED_PASTE.sub("", text.lstrip("\ufeff"))

    variables: dict[str, str] = {}
    for lineno, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        name, sep, raw = stripped.partition("=")
        if not sep:
            raise RailwayVarsError(f"line {lineno}: no '=' in {stripped[:40]!r}")
        name = name.strip()
        raw = raw.strip()
        if not _NAME.match(name):
            raise RailwayVarsError(
                f"line {lineno}: {name!r} is not a valid variable name. The repr is "
                "shown because the offending character is usually invisible — a "
                "non-breaking space or a zero-width character picked up from the page."
            )
        if raw.startswith('"'):
            try:
                variables[name] = json.loads(raw)
            except json.JSONDecodeError as e:
                raise RailwayVarsError(
                    f"line {lineno}: {name} is quoted but not valid JSON ({e.msg}). "
                    "Paste the Raw Editor's contents unmodified."
                ) from e
        else:
            variables[name] = raw
        found = _CONTROL.search(variables[name])
        if found:
            raise RailwayVarsError(
                f"line {lineno}: {name} contains a control character "
                f"({found.group()!r}) — refusing to write it. Escape sequences in a "
                "value can rewrite any terminal that later prints it."
            )
    if not variables:
        raise RailwayVarsError("no variables found — is the file empty?")

    # Self-check on the decoder rather than on Railway: FOLLOWABLES is our own variable
    # and is always a JSON object, so if it decoded correctly the quoting was handled
    # correctly. A parser that silently half-works is the failure mode here.
    followables = variables.get("FOLLOWABLES")
    if followables is not None:
        try:
            json.loads(followables)
        except json.JSONDecodeError as e:
            raise RailwayVarsError(
                "FOLLOWABLES did not survive parsing, so the quoting was misread — "
                f"refusing to write anything ({e.msg})"
            ) from e
    return variables


def build_snapshot(
    environment: str, services: t.Sequence[str], *, now: dt.datetime
) -> dict[str, t.Any]:
    return {
        "environment": environment,
        "captured_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
        "services": {svc: fetch(svc, environment) for svc in services},
    }


def _counts(snapshot: dict[str, t.Any]) -> str:
    lines = []
    for svc, variables in snapshot["services"].items():
        keep = sum(1 for k, v in variables.items() if restorable(k, v)[0])
        lines.append(f"  {svc:<10} {len(variables):>3} captured, {keep:>3} restorable")
    return "\n".join(lines)


def _do_dump(args: argparse.Namespace) -> int:
    now = dt.datetime.now(tz=dt.UTC)
    snapshot = build_snapshot(args.environment, args.services, now=now)
    out = pathlib.Path(
        args.out
        or f"kyber-{args.environment}-vars-{now.strftime('%Y%m%dT%H%M%SZ')}.json"
    )
    out.write_text(json.dumps(snapshot, indent=2, sort_keys=True) + "\n")
    out.chmod(0o600)  # secrets: not world-readable, same as an ssh key
    print(f"Wrote {out}  ({args.environment})")
    print(_counts(snapshot))
    print(
        "\nThis file contains live secrets in plaintext. It is gitignored; keep it "
        "somewhere you would keep a database dump."
    )
    return 0


def plan_restore(
    snapshot: dict[str, t.Any], live: dict[str, dict[str, str]]
) -> dict[str, dict[str, tuple[str, str]]]:
    """What a restore of ``snapshot`` over ``live`` would do, per service and name.

    Returns ``{service: {name: (action, value)}}``, where ``action`` is ``set`` (absent
    or different), ``same``, or ``skipped``.
    """
    plan: dict[str, dict[str, tuple[str, str]]] = {}
    for svc, variables in snapshot["services"].items():
        current = live.get(svc, {})
        entries: dict[str, tuple[str, str]] = {}
        for name, value in sorted(variables.items()):
            allowed, _why = restorable(name, value)
            if not allowed:
                entries[name] = ("skipped", value)
            elif current.get(name) == value:
                entries[name] = ("same", value)
            else:
                entries[name] = ("set", value)
        plan[svc] = entries
    return plan


def _format_plan(plan: dict[str, dict[str, tuple[str, str]]], *, execute: bool) -> str:
    lines: list[str] = []
    total = 0
    for svc, entries in plan.items():
        to_set = [n for n, (a, _) in entries.items() if a == "set"]
        same = sum(1 for a, _ in entries.values() if a == "same")
        skipped = sum(1 for a, _ in entries.values() if a == "skipped")
        total += len(to_set)
        lines.append(
            f"\n  {svc}: {len(to_set)} to set, {same} unchanged, {skipped} skipped"
        )
        for name in to_set:
            # Never the value: this runs in a terminal and the values are secrets.
            lines.append(f"    set  {name}")
    lines.append("")
    lines.append(
        f"  {total} variable(s) to write."
        + ("" if execute else "  DRY RUN — nothing written. Re-run with --execute.")
    )
    return "\n".join(lines)


def apply_restore(
    environment: str, plan: dict[str, dict[str, tuple[str, str]]]
) -> None:
    for svc, entries in plan.items():
        sets: list[str] = []
        for name, (action, value) in entries.items():
            if action == "set":
                sets.extend(["--set", f"{name}={value}"])
        if not sets:
            continue
        # --skip-deploys throughout: a restore is a config repair, and a redeploy is a
        # separate decision the operator should be making deliberately.
        _railway(["variables", "-s", svc, "-e", environment, "--skip-deploys", *sets])


def _do_restore(args: argparse.Namespace) -> int:
    path = pathlib.Path(args.file)
    if not path.is_file():
        raise RailwayVarsError(f"{path} does not exist")
    snapshot = json.loads(path.read_text())
    environment = args.environment or snapshot.get("environment")
    if not environment:
        raise RailwayVarsError("the snapshot names no environment; pass --environment")
    # Restoring prod's variables into dev (or the reverse) would be quiet and very hard
    # to unpick, so crossing environments has to be said out loud twice.
    if (
        args.environment
        and snapshot.get("environment") != args.environment
        and not args.force_cross_environment
    ):
        raise RailwayVarsError(
            f"snapshot is from {snapshot.get('environment')!r} but you asked for "
            f"{args.environment!r} — pass --force-cross-environment if you mean it"
        )

    print(f"Restoring {path.name} ({snapshot.get('captured_at')}) into {environment}")
    live = {svc: fetch(svc, environment) for svc in snapshot["services"]}
    plan = plan_restore(snapshot, live)
    print(_format_plan(plan, execute=args.execute))
    if args.execute:
        apply_restore(environment, plan)
        print("\nWritten, with --skip-deploys. Redeploy when you are ready.")
    return 0


def _read_raw_source(spec: str) -> tuple[str, str]:
    """The Raw Editor text and a label for it, from a path or from stdin (``-``).

    Pasting into a terminal is the intended path — you are copying out of a browser, so
    a file is a step that exists only to be deleted afterwards. Two notes on it. The
    prompt goes to stderr so piping still works. And a terminal in canonical mode
    truncates any *line* over 4096 bytes: the longest line here is ~1800 (the Google
    service-account key), so there is headroom, and a truncated line would lose its
    closing quote and be rejected by :func:`parse_raw` rather than written half-formed.
    """
    if spec == "-":
        if sys.stdin.isatty():
            print(
                "Paste the Raw Editor contents, then press Ctrl-D on a blank line.\n"
                "(Railway → the service → Variables → the ⋮ menu → Raw Editor)",
                file=sys.stderr,
            )
        return sys.stdin.read(), "the paste"
    path = pathlib.Path(spec)
    if not path.is_file():
        raise RailwayVarsError(f"{path} does not exist")
    return path.read_text(), path.name


def _do_restore_raw(args: argparse.Namespace) -> int:
    text, label = _read_raw_source(args.file)
    variables = parse_raw(text)
    refs = sum(1 for v in variables.values() if is_reference(v))
    print(
        f"Read {len(variables)} variable(s) from {label} — {refs} reference(s), "
        f"{len(variables) - refs} literal(s)"
    )
    snapshot = {
        "environment": args.environment,
        "captured_at": "(raw editor paste)",
        "services": {args.service: variables},
    }
    live = {args.service: fetch(args.service, args.environment)}
    plan = plan_restore(snapshot, live)
    print(_format_plan(plan, execute=args.execute))
    if args.execute:
        apply_restore(args.environment, plan)
        print("\nWritten, with --skip-deploys. Redeploy when you are ready.")
    return 0


def _csv(spec: str) -> tuple[str, ...]:
    return tuple(part.strip() for part in spec.split(",") if part.strip())


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m dd.common.railway_vars",
        description="Snapshot a Railway environment's variables, and restore them.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    dump = sub.add_parser("dump", help="write every service variable to a JSON file")
    dump.add_argument("--environment", required=True)
    dump.add_argument("--services", type=_csv, default=DEFAULT_SERVICES)
    dump.add_argument("--out", default=None)
    dump.set_defaults(func=_do_dump)

    restore = sub.add_parser("restore", help="put a snapshot's variables back")
    restore.add_argument("--file", required=True)
    restore.add_argument(
        "--environment",
        default=None,
        help="defaults to the environment the snapshot was taken from",
    )
    restore.add_argument("--execute", action="store_true")
    restore.add_argument("--force-cross-environment", action="store_true")
    restore.set_defaults(func=_do_restore)

    raw = sub.add_parser(
        "restore-raw",
        help="put back a paste of the web Raw Editor (preserves ${{...}} references)",
    )
    raw.add_argument(
        "--file", default="-", help="a file, or '-' (the default) to read the paste"
    )
    raw.add_argument("--service", required=True)
    raw.add_argument("--environment", required=True)
    raw.add_argument("--execute", action="store_true")
    raw.set_defaults(func=_do_restore_raw)

    compare_cmd = sub.add_parser(
        "compare",
        help="list variables beacon has and anchor does not (exit 1 if any)",
    )
    compare_cmd.add_argument("--environment", required=True)
    compare_cmd.set_defaults(func=_do_compare)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        return t.cast(int, args.func(args))
    except RailwayVarsError as e:
        print(f"railway_vars: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
