"""baseline schema

The whole of dd.common.schemas.Base.metadata as of the move from Atlas to Alembic.
The Atlas migration history it replaces was MySQL DDL and is not convertible, so this
starts from an empty database: the Postgres deployment is created fresh (git history
still holds the old `migrations/*.sql` if they are ever needed).

Revision ID: b7df22b81517
Revises:
Create Date: 2026-08-05 22:56:39.226363+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b7df22b81517"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_emoji_cache",
        sa.Column("app_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("emoji_id", sa.BigInteger(), nullable=False),
        sa.Column("icon_url", sa.VARCHAR(length=256), nullable=False),
        sa.Column("last_used", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("app_id", "name"),
    )
    op.create_index(
        "ix_app_emoji_emoji_id", "app_emoji_cache", ["emoji_id"], unique=False
    )
    op.create_index(
        "ix_app_emoji_lru", "app_emoji_cache", ["app_id", "last_used"], unique=False
    )
    op.create_table(
        "auto_post_settings",
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("value", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "autopost_daily_stat",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("feed", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("date", "feed", "kind"),
    )
    op.create_table(
        "bungie_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("refresh_token", sa.VARCHAR(length=1024), nullable=True),
        sa.Column("refresh_token_expires", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "command_usage",
        sa.Column("command_name", sa.String(length=128), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("command_name", "date"),
    )
    op.create_table(
        "cv2_draft",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.VARCHAR(length=8), nullable=False),
        sa.Column("nodes", sa.JSON(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=True),
        sa.Column("target_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("target_message_id", sa.BigInteger(), nullable=True),
        sa.Column("published_message_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_cv2_draft_created_at", "cv2_draft", ["created_at"], unique=False
    )
    op.create_table(
        "mirror_delivery",
        sa.Column("src_msg_id", sa.BigInteger(), nullable=False),
        sa.Column("dest_ch_id", sa.BigInteger(), nullable=False),
        sa.Column("src_ch_id", sa.BigInteger(), nullable=False),
        sa.Column("dest_msg_id", sa.BigInteger(), nullable=True),
        sa.Column("desired_version", sa.Integer(), nullable=False),
        sa.Column("applied_version", sa.Integer(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("crosspost_state", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(), nullable=False),
        sa.Column("last_error_ref", sa.String(length=8), nullable=True),
        sa.Column("last_error_class", sa.String(length=12), nullable=True),
        sa.Column("last_error_msg", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("src_msg_id", "dest_ch_id"),
    )
    op.create_index(
        "ix_mirror_delivery_created_at", "mirror_delivery", ["created_at"], unique=False
    )
    op.create_index(
        "ix_mirror_delivery_crosspost_due",
        "mirror_delivery",
        ["crosspost_state", "due_at"],
        unique=False,
    )
    op.create_index(
        "ix_mirror_delivery_state_due",
        "mirror_delivery",
        ["state", "due_at"],
        unique=False,
    )
    op.create_table(
        "mirror_message_version",
        sa.Column("src_msg_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.Column("src_guild_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("summary", sa.String(length=200), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("src_msg_id", "version"),
    )
    op.create_index(
        "ix_mirror_message_version_captured_at",
        "mirror_message_version",
        ["captured_at"],
        unique=False,
    )
    op.create_table(
        "mirror_operation_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("src_msg_id", sa.BigInteger(), nullable=False),
        sa.Column("src_ch_id", sa.BigInteger(), nullable=True),
        sa.Column("op_type", sa.String(length=8), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("delivered", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("cancelled", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("failure_refs", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mirror_operation_log_finished_at",
        "mirror_operation_log",
        ["finished_at"],
        unique=False,
    )
    op.create_index(
        "ix_mirror_operation_log_src_msg_id",
        "mirror_operation_log",
        ["src_msg_id"],
        unique=False,
    )
    op.create_table(
        "mirrored_channel",
        sa.Column("src_id", sa.BigInteger(), nullable=False),
        sa.Column("dest_id", sa.BigInteger(), nullable=False),
        sa.Column("dest_server_id", sa.BigInteger(), nullable=True),
        sa.Column("legacy", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("role_mention_id", sa.BigInteger(), nullable=True),
        sa.Column("unreachable_since", sa.DateTime(), nullable=True),
        sa.Column("legacy_disable_for_failure_on_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("src_id", "dest_id"),
        sa.UniqueConstraint("src_id", "dest_id", name="_mir_ids_uc"),
    )
    op.create_table(
        "rotation_data",
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "server_statistics",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("population", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_command",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("l1_name", sa.String(length=32), nullable=True),
        sa.Column("l2_name", sa.String(length=32), nullable=True),
        sa.Column("l3_name", sa.String(length=32), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("response_type", sa.Integer(), nullable=True),
        sa.Column("response_data", sa.Text(), nullable=True),
        sa.CheckConstraint("(l2_name = '' AND l3_name = '') OR (l2_name <> '')"),
        sa.CheckConstraint("l3_name = '' OR response_type <> 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("l1_name", "l2_name", "l3_name", name="_ln_name_uc"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_command")
    op.drop_table("server_statistics")
    op.drop_table("rotation_data")
    op.drop_table("mirrored_channel")
    op.drop_index(
        "ix_mirror_operation_log_src_msg_id", table_name="mirror_operation_log"
    )
    op.drop_index(
        "ix_mirror_operation_log_finished_at", table_name="mirror_operation_log"
    )
    op.drop_table("mirror_operation_log")
    op.drop_index(
        "ix_mirror_message_version_captured_at", table_name="mirror_message_version"
    )
    op.drop_table("mirror_message_version")
    op.drop_index("ix_mirror_delivery_state_due", table_name="mirror_delivery")
    op.drop_index("ix_mirror_delivery_crosspost_due", table_name="mirror_delivery")
    op.drop_index("ix_mirror_delivery_created_at", table_name="mirror_delivery")
    op.drop_table("mirror_delivery")
    op.drop_index("ix_cv2_draft_created_at", table_name="cv2_draft")
    op.drop_table("cv2_draft")
    op.drop_table("command_usage")
    op.drop_table("bungie_credentials")
    op.drop_table("autopost_daily_stat")
    op.drop_table("auto_post_settings")
    op.drop_index("ix_app_emoji_lru", table_name="app_emoji_cache")
    op.drop_index("ix_app_emoji_emoji_id", table_name="app_emoji_cache")
    op.drop_table("app_emoji_cache")
    # ### end Alembic commands ###
